CREATE TABLE "type_user" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) UNIQUE NOT NULL
);

CREATE TABLE "status" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) UNIQUE NOT NULL,
  "description" text
);

CREATE TABLE "entreprise" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) UNIQUE NOT NULL,
  "address" text NOT NULL,
  "phone" varchar(20),
  "email" varchar(100) UNIQUE
);

CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar(50) UNIQUE NOT NULL,
  "type_user_id" int NOT NULL,
  "email" varchar(100) UNIQUE NOT NULL,
  "password_hash" varchar(255) NOT NULL,
  "login_attempts" int DEFAULT 0,
  "is_blocked" boolean DEFAULT false,
  "blocked_at" timestamp,
  "last_login" timestamp
);

CREATE TABLE "sessions" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "token" varchar(255) UNIQUE NOT NULL,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "expires_at" timestamp NOT NULL,
  "is_active" boolean DEFAULT true,
  "last_activity" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "signalement" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "latitude" decimal(10,8) NOT NULL,
  "longitude" decimal(11,8) NOT NULL,
  "description" text NOT NULL,
  "date_signalement" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "status_id" int NOT NULL,
  "surface_area" decimal(10,2),
  "budget" decimal(15,2),
  "entreprise_id" int,
  "photo_url" varchar(255)
);

CREATE TABLE "signalement_status" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "signalement_id" int NOT NULL,
  "status_id" int NOT NULL,
  "changed_by" int,
  "date_status" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "comment" text
);

COMMENT ON COLUMN "users"."login_attempts" IS 'CHECK login_attempts >= 0';

ALTER TABLE "users" ADD FOREIGN KEY ("type_user_id") REFERENCES "type_user" ("id");

ALTER TABLE "sessions" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "signalement" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "signalement" ADD FOREIGN KEY ("status_id") REFERENCES "status" ("id");

ALTER TABLE "signalement" ADD FOREIGN KEY ("entreprise_id") REFERENCES "entreprise" ("id");

ALTER TABLE "signalement_status" ADD FOREIGN KEY ("signalement_id") REFERENCES "signalement" ("id");

ALTER TABLE "signalement_status" ADD FOREIGN KEY ("status_id") REFERENCES "status" ("id");

ALTER TABLE "signalement_status" ADD FOREIGN KEY ("changed_by") REFERENCES "users" ("id");
